---
title: "Notebook Simulation Guanglong Model"
params: 
  base_import_path:
    value: "D:/Projekte/Digital-Identity/data_science/"
  output_path: 
    value: "D:/Projekte/Digital-Identity/data_science/workbooks/plots/test/"
  T_s:
    value: 0.014
    input: numeric
  sample_size: 
    value: 300
    input: numeric
  x_initial_state_q0:
    value: 1.0
    input: numeric
  x_initial_state_q1:
    value: 0.0
    input: numeric
  x_initial_state_q2:
    value: 0.0
    input: numeric
  x_initial_state_q3:
    value: 0.0
    input: numeric
  x_initial_state_euler_vx:
    value: 0.00000000000001
    input: numeric
  x_initial_state_euler_vy:
    value: 0.00000000000001
    input: numeric
  x_initial_state_euler_vz:
    value: 0.00000000000001
    input: numeric
  initial_belief_00_q0:
    value: 0.05
    input: numeric
  initial_belief_11_q1:
    value: 0.05
    input: numeric
  initial_belief_22_q2:
    value: 0.05
    input: numeric
  initial_belief_33_q3:
    value: 0.05
    input: numeric
  initial_belief_44_euler_vx:
    value: 2.1
    input: numeric
  initial_belief_55_euler_vy:
    value: 2.1
    input: numeric
  initial_belief_66_euler_vz:
    value: 2.1
    input: numeric
  process_noise_orientation_angular_velocity_sigma_x:
    value: 0.05
    input: numeric
  process_noise_orientation_angular_velocity_sigma_y:
    value: 0.05
    input: numeric
  process_noise_orientation_angular_velocity_sigma_z:
    value: 0.05
    input: numeric
  sensor_noise_imu_euler_velocity_x:
    value: 0.01
    input: numeric
  sensor_noise_imu_euler_velocity_y:
    value: 0.01
    input: numeric
  sensor_noise_imu_euler_velocity_z:
    value: 0.01
    input: numeric
  x_initial_state_px:
    value: 0.0000000000001
    input: numeric
  x_initial_state_vx:
    value: 0.0000000000001
    input: numeric
  x_initial_state_ax:
    value: 0.0000000000001
    input: numeric
  x_initial_state_py:
    value: 0.0000000000001
    input: numeric
  x_initial_state_vy:
    value: 0.0000000000001
    input: numeric
  x_initial_state_ay:
    value: 0.0000000000001
    input: numeric
  x_initial_state_pz:
    value: 0.0000000000001
    input: numeric
  x_initial_state_vz:
    value: 0.0000000000001
    input: numeric
  x_initial_state_az:
    value: 9.81
    input: numeric
  initial_belief_px_00:
    value: 0.31
    input: numeric
  initial_belief_vx_11:
    value: 0.31
    input: numeric
  initial_belief_ax_22:
    value: 0.31
    input: numeric
  initial_belief_py_33:
    value: 0.31
    input: numeric
  initial_belief_vy_44:
    value: 0.31
    input: numeric
  initial_belief_ay_55:
    value: 0.31
    input: numeric
  initial_belief_pz_66:
    value: 0.31
    input: numeric
  initial_belief_vz_77:
    value: 0.31
    input: numeric
  initial_belief_az_88:
    value: 0.31
    input: numeric
  process_noise_acceleration_noise_omega_x:
    value: 0.05
    input: numeric
  process_noise_acceleration_noise_omega_y:
    value: 0.05
    input: numeric
  process_noise_acceleration_noise_omega_z:
    value: 0.05
    input: numeric
  sensor_noise_kinect_sigma_x:
    value: 0.01
    input: numeric
  sensor_noise_kinect_sigma_y:
    value: 0.01
    input: numeric
  sensor_noise_kinect_sigma_z:
    value: 0.01
    input: numeric
  sensor_noise_imu_sigma_x:
    value: 0.05
    input: numeric
  sensor_noise_imu_sigma_y:
    value: 0.05
    input: numeric
  sensor_noise_imu_sigma_z:
    value: 0.05
    input: numeric
  simulation_acceleration_process_noise_x:
    value: 0
    input: numeric
  simulation_acceleration_process_noise_y:
    value: 0
    input: numeric
  simulation_acceleration_process_noise_z:
    value: 0
    input: numeric
  simulation_position_sensor_noise_x:
    value: 0
    input: numeric
  simulation_position_sensor_noise_y:
    value: 0
    input: numeric
  simulation_position_sensor_noise_z:
    value: 0
    input: numeric
  simulation_acceleration_sensor_noise_x:
    value: 0
    input: numeric
  simulation_acceleration_sensor_noise_y:
    value: 0
    input: numeric
  simulation_acceleration_sensor_noise_z:
    value: 0
    input: numeric
  simulation_orientation_process_angle_velocity_noise_x:
    value: 0
    input: numeric
  simulation_orientation_process_angle_velocity_noise_y:
    value: 0
    input: numeric
  simulation_orientation_process_angle_velocity_noise_z:
    value: 0
    input: numeric
  simulation_orientation_sensor_angle_velocity_noise_x:
    value: 0
    input: numeric
  simulation_orientation_sensor_angle_velocity_noise_y:
    value: 0
    input: numeric
  simulation_orientation_sensor_angle_velocity_noise_z:
    value: 0
    input: numeric
---

```{r, echo=FALSE}
# Install Libraries, when necessary

#install.packages("RMThreshold")
#install.packages("jsonlite")
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("patchwork")
#install.packages("reshape2")
#install.packages("RSpincalc")
#install.packages("LaplacesDemon")
#install.packages('Rcpp')
#install.packages('KFK')
#install.packages("shiny")
```

```{r, echo=FALSE}
# Load Libraries

library(shiny)
library(dplyr)
library(RMThreshold)
library(ggplot2)
library(RSpincalc)
library(reshape2)
library(LaplacesDemon)
library(Rcpp)
library(FKF)
library(yaml)
```

```{r, echo=FALSE}
# Create the directory for the plots 
if(!dir.exists(params$output_path)){
  dir.create(params$output_path)
}
fileConn<-file(paste(params$output_path,"params.txt", sep = ""))
writeLines(as.yaml(params), fileConn)
close(fileConn)
```

```{r, echo=FALSE}
# Execute this line of code to load self implemented functions

source(paste(params$base_import_path, "/scripts/functions.R",sep=""))

Ts = params$T_s
simulatedMax = params$sample_size

```

```{r, echo=FALSE}
# Here is the definition of the state space model
# Will need euler angle velocity sensor
source(paste(params$base_import_path, "/scripts/models.R",sep=""))
```

```{r, echo=FALSE}

# Init the state space models

initial_orientation_state = c(
  params$x_initial_state_q0, 
  params$x_initial_state_q1,
  params$x_initial_state_q2,
  params$x_initial_state_q3,
  params$x_initial_state_euler_vx,
  params$x_initial_state_euler_vy,
  params$x_initial_state_euler_vz
)

initial_orientation_belief = diag(
  c(
    params$initial_belief_00_q0,  
    params$initial_belief_11_q1,
    params$initial_belief_22_q2,
    params$initial_belief_33_q3,
    params$initial_belief_44_euler_vx,
    params$initial_belief_55_euler_vy,
    params$initial_belief_66_euler_vz
    )
)

orientation_process_noise = data.frame(
  vx = params$process_noise_orientation_angular_velocity_sigma_x,
  vy = params$process_noise_orientation_angular_velocity_sigma_y,
  vz = params$process_noise_orientation_angular_velocity_sigma_z
)

orientation_sensor_noise = data.frame(
  vx = params$sensor_noise_imu_euler_velocity_x,
  vy = params$sensor_noise_imu_euler_velocity_y,
  vz = params$sensor_noise_imu_euler_velocity_z
)
#

processOrientationModel = getGuanglongOrientationModel(Ts, initial_orientation_state, initial_orientation_belief, orientation_process_noise, orientation_sensor_noise)

simulation_rotation_quaternion = data.frame(
  w = array(data = 1, dim = simulatedMax),
  x = array(data = 0, dim = simulatedMax),
  y = array(data = 0, dim = simulatedMax),
  z = array(data = 0, dim = simulatedMax)
)

## only for simulation, this should be the kinect quaternion with real data
rotationMatrix = quaternion_rotation_matrix(
  simulation_rotation_quaternion$w[1],
  simulation_rotation_quaternion$x[1],
  simulation_rotation_quaternion$y[1],
  simulation_rotation_quaternion$z[1]
  )

initial_matrixHandToLocal = data.frame(
  mx_x = rotationMatrix[1,1], my_x = rotationMatrix[1,2], mz_x = rotationMatrix[1,3],
  mx_y = rotationMatrix[2,1], my_y = rotationMatrix[2,2], mz_y = rotationMatrix[2,3],
  mx_z = rotationMatrix[3,1], my_z = rotationMatrix[3,2], mz_z = rotationMatrix[3,3]
)

## only for simulation
initial_gravity = data.frame(
  x = 0,
  y = 0,
  z = 0
  )
##

initial_acceleration_state = c(
  params$x_initial_state_px,
  params$x_initial_state_vx,
  params$x_initial_state_ax,
  params$x_initial_state_py,
  params$x_initial_state_vy,
  params$x_initial_state_ay,
  params$x_initial_state_pz,
  params$x_initial_state_vz,
  params$x_initial_state_az
)

initial_acceleration_belief = diag(c(
  params$initial_belief_px_00,
  params$initial_belief_vx_11,
  params$initial_belief_ax_22,
  params$initial_belief_py_33,
  params$initial_belief_vy_44,
  params$initial_belief_ay_55,
  params$initial_belief_pz_66,
  params$initial_belief_vz_77,
  params$initial_belief_az_88
))

acceleration_process_noise = data.frame(
  x = params$process_noise_acceleration_noise_omega_x,
  y = params$process_noise_acceleration_noise_omega_y,
  z = params$process_noise_acceleration_noise_omega_z
)

acceleration_sensor_noise = data.frame(
  x = params$sensor_noise_kinect_sigma_x,
  y = params$sensor_noise_kinect_sigma_y,
  z = params$sensor_noise_kinect_sigma_z,
  ax = params$sensor_noise_imu_sigma_x,
  ay = params$sensor_noise_imu_sigma_y,
  az = params$sensor_noise_imu_sigma_z
)

processAccelerationModel = getGuanglongAccelerationModel(Ts, initial_acceleration_state, initial_acceleration_belief, initial_matrixHandToLocal, initial_gravity, acceleration_process_noise, acceleration_sensor_noise)

```

```{r, echo=FALSE}

# The following chunk generates data from an simulator for orientation

# Simulation of orientation

orientation_process_noise = data.frame(
  vx = params$process_noise_orientation_angular_velocity_sigma_x,
  vy = params$process_noise_orientation_angular_velocity_sigma_y,
  vz = params$process_noise_orientation_angular_velocity_sigma_z
)


simulation_orientation_process_noise = data.frame(
  vx = params$simulation_orientation_process_angle_velocity_noise_x,
  vy = params$simulation_orientation_process_angle_velocity_noise_y,
  vz = params$simulation_orientation_process_angle_velocity_noise_z
)

simulation_orientation_sensor_noise = data.frame(
  vx = params$simulation_orientation_sensor_angle_velocity_noise_x,
  vy = params$simulation_orientation_sensor_angle_velocity_noise_y,
  vz = params$simulation_orientation_sensor_angle_velocity_noise_z
)

simulation_acceleration_process_noise = data.frame(
  x = params$simulation_acceleration_sensor_noise_x,
  y = params$simulation_acceleration_sensor_noise_y,
  z = params$simulation_acceleration_sensor_noise_z
)

simulation_acceleration_sensor_noise = data.frame(
  x  = params$simulation_acceleration_process_noise_x,
  y  = params$simulation_acceleration_process_noise_y,
  z  = params$simulation_acceleration_process_noise_z,
  ax = params$simulation_position_sensor_noise_x,
  ay = params$simulation_position_sensor_noise_y,
  az = params$simulation_position_sensor_noise_z
)

source(paste(params$base_import_path, "/scripts/simulation.R",sep=""))

# Simulation Data for Orientation

setOrientationSimulationModell(processOrientationModel)
setOrientationSimulationProcessNoise(simulation_orientation_process_noise)
setOrientationSimulationSensorNoise(simulation_orientation_sensor_noise)
setOrientationSimulationIndex(1)

simulated_normalized_quaternions = matrix(data = c(
  1,
  0,
  0,
  0
  ), nrow = simulatedMax, ncol=4, byrow = TRUE)

x_k = as.double(initial_orientation_state)
simulationOrientationData = Reduce(x = lapply(1:simulatedMax, justReturn, x_k), f=generateNextOrientationFrame, accumulate = TRUE)
simulationOrientationMeasurements = lapply(simulationOrientationData, generateNextOrientationMeasurement)

simulatedOrientationDataAsMatrix = matrix(data = unlist(simulationOrientationData), nrow = 7, ncol=simulatedMax)
simulationOrientationMeasurementsAsMatrix = matrix(data = unlist(simulationOrientationMeasurements), nrow = 3, ncol=simulatedMax)

simulated_normalized_quaternions = matrix(data = c(
  simulatedOrientationDataAsMatrix[1,],
  simulatedOrientationDataAsMatrix[2,],
  simulatedOrientationDataAsMatrix[3,],
  simulatedOrientationDataAsMatrix[4,]
  ), nrow = simulatedMax, ncol=4)

simulatedfkfGuanglongOrientationModel = fkf(
  a0 = processOrientationModel$x[,1],
  P0 = processOrientationModel$P,
  dt = matrix(data = 0, nrow = 7, ncol = 1),
  ct = matrix(data = 0, nrow = 3, ncol = 1),
  GGt = diag(nrow = 3, ncol = 3),
  Zt = processOrientationModel$H,
  Tt = array(as.numeric(unlist(lapply(1:simulatedMax, simulated_orientation_transition_at_index))), dim=c(7, 7, simulatedMax)),
  HHt = processOrientationModel$Q,
  yt = matrix(data = c(
    simulationOrientationMeasurementsAsMatrix[1,],
    simulationOrientationMeasurementsAsMatrix[2,],
    simulationOrientationMeasurementsAsMatrix[3,]
  ), nrow = 3, ncol = simulatedMax, byrow = TRUE)
)

normalizedOrientationState = normalizeQuaternion(
  simulatedfkfGuanglongOrientationModel$att[1,1:simulatedMax],
  simulatedfkfGuanglongOrientationModel$att[2,1:simulatedMax],
  simulatedfkfGuanglongOrientationModel$att[3,1:simulatedMax],
  simulatedfkfGuanglongOrientationModel$att[4,1:simulatedMax]
)

simulation_rotation_quaternion = data.frame(
  w = array(data = normalizedOrientationState$w, dim = simulatedMax),
  x = array(data = normalizedOrientationState$x, dim = simulatedMax),
  y = array(data = normalizedOrientationState$y, dim = simulatedMax),
  z = array(data = normalizedOrientationState$z, dim = simulatedMax)
)

# Simulation Data for Position

setAccelerationSimulationModell(processAccelerationModel)
setAccelerationSimulationProcessNoise(simulation_acceleration_process_noise)
setAccelerationSimulationSensorNoise(simulation_acceleration_sensor_noise)
setAccelerationSimulationIndex(1)

x_k = as.double(initial_acceleration_state)

base_gravity = data.frame(x = rep(0,times=simulatedMax), y = rep(0,times=simulatedMax), z = rep(9.81,times=simulatedMax))

gravity = rotate_vector_by(base_gravity, simulation_rotation_quaternion)

# With gravity
simulationAccelerationData = Reduce(x = lapply(1:simulatedMax, justReturn, x_k), f=generateNextAccelerationFrameWithGravity, accumulate = TRUE)

#simulationAccelerationData = lapply(simulationAccelerationData, function(data) data + c(0,0,gravity$x,0,0,gravity$y,0,0,gravity$z))
# without gravity
#simulationAccelerationData = Reduce(x = lapply(1:simulatedMax, justReturn,x_k), f=generateNextAccelerationFrame, accumulate = TRUE)

simulationAccelerationMeasurements = lapply(simulationAccelerationData, generateNextAccelerationMeasurement)

simulatedDataAccAsMatrix = matrix(data = unlist(simulationAccelerationData), nrow = 9, ncol=simulatedMax)

#simulatedDataAccAsMatrix[3,] = simulatedDataAccAsMatrix[3,] + gravity$x
#simulatedDataAccAsMatrix[6,] = simulatedDataAccAsMatrix[6,] + gravity$y
#simulatedDataAccAsMatrix[9,] = simulatedDataAccAsMatrix[9,] + gravity$z

simulationAccelerationMeasurementsAsMatrix = matrix(data = unlist(simulationAccelerationMeasurements), nrow = 6, ncol=simulatedMax)

#simulationAccelerationMeasurementsAsMatrix[2,] = simulationAccelerationMeasurementsAsMatrix[2,] + gravity$x
#simulationAccelerationMeasurementsAsMatrix[4,] = simulationAccelerationMeasurementsAsMatrix[4,] + gravity$y
#simulationAccelerationMeasurementsAsMatrix[6,] = simulationAccelerationMeasurementsAsMatrix[6,] + gravity$z

#processAccelerationModel$x[,1][9] = 9.81

  
simulatedfkfGuanglongAccelerationModel = fkf(
  a0 = processAccelerationModel$x[,1],
  P0 = processAccelerationModel$P,
  dt = matrix(data = c(
    -gravity$x * Ts**2/2,
    -gravity$x * Ts,
    rep(0,times=simulatedMax),
    -gravity$y * Ts**2/2,
    -gravity$y * Ts,
    rep(0,times=simulatedMax),
    -gravity$z * Ts**2/2,
    -gravity$z * Ts,
    rep(0,times=simulatedMax)
  ), nrow = 9, ncol = simulatedMax, byrow = TRUE),
  #ct = matrix(data = c(0,0,0, 0, 0,0), nrow = 6, ncol = 1),
  ct = matrix(data = c(
    rep(0,times=simulatedMax),
    rep(0,times=simulatedMax),
    rep(0,times=simulatedMax),
    rep(0,times=simulatedMax),
    rep(0,times=simulatedMax),
    rep(0,times=simulatedMax)
  ), nrow = 6, ncol = simulatedMax, byrow = TRUE),
  GGt = diag(x= c(1,1,1,1,1,1)),
  Zt = processAccelerationModel$H,
  Tt = array(as.numeric(unlist(lapply(1:simulatedMax,acceleration_simulation_transition_at_index))), dim=c(9, 9, simulatedMax)),
  HHt = processAccelerationModel$Q,
  yt = matrix(data = c(
    simulationAccelerationMeasurementsAsMatrix[1,],
    simulationAccelerationMeasurementsAsMatrix[2,],
    simulationAccelerationMeasurementsAsMatrix[3,],
    simulationAccelerationMeasurementsAsMatrix[4,],
    simulationAccelerationMeasurementsAsMatrix[5,],
    simulationAccelerationMeasurementsAsMatrix[6,]
  ), nrow = 6, ncol = simulatedMax, byrow = TRUE)
  )

sim_time = c(1:simulatedMax)
sim_time = sim_time * Ts

knitr::opts_chunk$set(fig.path = params$output_path)

```

## Orientation Plots

```{r, orientation, fig.show="hold", out.width="33%", echo=FALSE}

# Plot the orientation

plot_limit_offset = 0.5

plot(normalizedOrientationState$w[1:simulatedMax] ~ sim_time, pch  = 20, main = expression(q[w] ~ "state"), ylab = "value normalized", xlab="t in s", type='l', ylim=c(
  min(normalizedOrientationState$w[1:simulatedMax]) - plot_limit_offset, 
  max(normalizedOrientationState$w[1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[1,1,1:simulatedMax] + normalizedOrientationState$w[1:simulatedMax], rev(normalizedOrientationState$w[1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[1,1,1:simulatedMax] )),
  col = "lightsteelblue", 
  border = NA)
lines(normalizedOrientationState$w[1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(q[w] ~ "state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))


plot(normalizedOrientationState$x[1:simulatedMax] ~ sim_time, pch  = 20, main = expression(q[x] ~ "state"), ylab = "value normalized", xlab="t in s", type='l', ylim=c(
  min(normalizedOrientationState$x[1:simulatedMax]) - plot_limit_offset, 
  max(normalizedOrientationState$x[1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[2,2,1:simulatedMax] + normalizedOrientationState$x[1:simulatedMax], rev(normalizedOrientationState$x[1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[2,2,1:simulatedMax] )),
  col = "lightsteelblue", 
  border = NA)
lines(normalizedOrientationState$x[1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(q[x] ~ "state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))

plot(normalizedOrientationState$y[1:simulatedMax] ~ sim_time, pch  = 20, main = expression(q[y] ~ "state"), ylab = "value normalized", xlab="t in s", type='l', ylim=c(
  min(normalizedOrientationState$y[1:simulatedMax]) - plot_limit_offset, 
  max(normalizedOrientationState$y[1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[3,3,1:simulatedMax] + normalizedOrientationState$y[1:simulatedMax], rev(normalizedOrientationState$y[1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[3,3,1:simulatedMax] )),
  col = "lightsteelblue", 
  border = NA)
lines(normalizedOrientationState$y[1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(q[y] ~ "state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))

plot(normalizedOrientationState$z[1:simulatedMax] ~ sim_time, pch  = 20, main = expression(q[z] ~ "state"), ylab = "value normalized", xlab="t in s", type='l', ylim=c(
  min(normalizedOrientationState$z[1:simulatedMax]) - plot_limit_offset, 
  max(normalizedOrientationState$z[1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[4,4,1:simulatedMax] + normalizedOrientationState$z[1:simulatedMax], rev(normalizedOrientationState$z[1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[4,4,1:simulatedMax] )),
  col = "lightsteelblue", 
  border = NA)
lines(normalizedOrientationState$z[1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(q[z] ~ "state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))

plot(simulationOrientationMeasurementsAsMatrix[1,] ~ sim_time, pch  = 20, main = expression(omega[x] ~ "in simulation"), ylab = expression(omega[x] ~ "in °/s"), xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongOrientationModel$att[5,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[1,]) - plot_limit_offset, 
  max(simulatedfkfGuanglongOrientationModel$att[5,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[1,]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[5,5,1:simulatedMax] + simulatedfkfGuanglongOrientationModel$att[5,1:simulatedMax], rev(simulatedfkfGuanglongOrientationModel$att[5,1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[5,5,1:simulatedMax] )),
  col = "lightsteelblue", 
  border = NA)
lines(simulatedfkfGuanglongOrientationModel$att[5,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationOrientationMeasurementsAsMatrix[1,] ~ sim_time)
legend("bottomright", legend = c(expression(omega[x] ~ "state"), expression("simulated " ~ omega[x]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

plot(simulationOrientationMeasurementsAsMatrix[2,] ~ sim_time, pch  = 20, main = expression(omega[y] ~ "in simulation"), ylab = expression(omega[y] ~ "in °/s"), xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongOrientationModel$att[6,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[2,]) - plot_limit_offset,
  max(simulatedfkfGuanglongOrientationModel$att[6,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[2,]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[6,6,1:simulatedMax] + simulatedfkfGuanglongOrientationModel$att[6,1:simulatedMax], rev(simulatedfkfGuanglongOrientationModel$att[6,1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[6,6,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongOrientationModel$att[6,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationOrientationMeasurementsAsMatrix[2,] ~ sim_time)
legend("bottomright", legend = c(expression(omega[y] ~ "state"), expression("simulated " ~ omega[y]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))


plot(simulationOrientationMeasurementsAsMatrix[3,] ~ sim_time, pch  = 20, main = expression(omega[z] ~ "in simulation"), ylab = expression(omega[z] ~ "in °/s"), xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongOrientationModel$att[7,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[3,]) - plot_limit_offset,
  max(simulatedfkfGuanglongOrientationModel$att[7,1:simulatedMax], simulationOrientationMeasurementsAsMatrix[3,]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongOrientationModel$Ptt[7,7,1:simulatedMax] + simulatedfkfGuanglongOrientationModel$att[7,1:simulatedMax], rev(simulatedfkfGuanglongOrientationModel$att[7,1:simulatedMax] - simulatedfkfGuanglongOrientationModel$Ptt[7,7,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongOrientationModel$att[7,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationOrientationMeasurementsAsMatrix[3,] ~ sim_time)
legend("bottomright", legend = c(expression(omega[z] ~ "state"), expression("simulated " ~ omega[z]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

#plot(simulatedfkfGuanglongOrientationModel, type = "resid.qq")
```

## Acceleration Plots

```{r, acceleration, fig.show="hold", out.width="33%", echo=FALSE}

plot_limit_offset = 0.5

plot(simulationAccelerationMeasurementsAsMatrix[1,] ~ sim_time, pch  = 20, main = expression(p[x] ~ " in simulation"), ylab = expression(p[x] ~" in m"), xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[1,], simulatedfkfGuanglongAccelerationModel$att[1,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[1,], simulatedfkfGuanglongAccelerationModel$att[1,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[1,1,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[1,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[1,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[1,1,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[1,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationAccelerationMeasurementsAsMatrix[1,] ~ sim_time)
legend("bottomright", legend = c(expression(p[x] ~ " state"), expression("simulated " ~ p[x]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

plot(simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax] ~ sim_time, pch  = 20, main = expression(v[x] ~ " in simulation"), ylab = expression(v[x] ~" in m/s"),xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax]) - plot_limit_offset,
  max(simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[2,2,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[2,2,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[2,1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(v[x] ~ " state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))

plot(simulationAccelerationMeasurementsAsMatrix[2,] ~ sim_time, pch  = 20, main = expression(a[x] ~ " in simulation"), ylab = expression(a[x] ~" in m/" ~ s^2), xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[2,], simulatedfkfGuanglongAccelerationModel$att[3,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[2,], simulatedfkfGuanglongAccelerationModel$att[3,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[3,3,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[3,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[3,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[3,3,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[3,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationAccelerationMeasurementsAsMatrix[2,] ~ sim_time)
legend("bottomright", legend = c(expression(a[x] ~ " state"), expression("simulated " ~ a[x]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

plot(simulationAccelerationMeasurementsAsMatrix[3,] ~ sim_time, pch  = 20, main = expression(p[y] ~ " in simulation"), ylab = expression(p[y] ~" in m"),xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[3,], simulatedfkfGuanglongAccelerationModel$att[4,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[3,], simulatedfkfGuanglongAccelerationModel$att[4,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[4,4,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[4,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[4,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[4,4,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[4,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationAccelerationMeasurementsAsMatrix[3,] ~ sim_time)
legend("bottomright", legend = c(expression(p[y] ~ " state"), expression("simulated " ~ p[y]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))


plot(simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax] ~ sim_time, pch  = 20, main = expression(v[y] ~ " in simulation"), ylab = expression(v[y] ~" in  m/s"),xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax]) - plot_limit_offset,
  max(simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[5,5,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[5,5,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[5,1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(v[y] ~ " state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))


plot(simulationAccelerationMeasurementsAsMatrix[4,] ~ sim_time, pch  = 20, main = expression(a[y] ~ " in simulation"), ylab = expression(a[y] ~" in m/" ~ s^2),xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[4,], simulatedfkfGuanglongAccelerationModel$att[6,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[4,], simulatedfkfGuanglongAccelerationModel$att[6,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[6,6,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[6,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[6,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[6,6,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$at[6,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationAccelerationMeasurementsAsMatrix[4,] ~ sim_time)
legend("bottomright", legend = c(expression(a[y] ~ " state"), expression("simulated " ~ a[y]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

plot(simulationAccelerationMeasurementsAsMatrix[5,] ~ sim_time, pch  = 20, main = expression(p[z] ~ " in simulation"), ylab = expression(p[z] ~" in m"),xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[5,], simulatedfkfGuanglongAccelerationModel$att[7,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[5,], simulatedfkfGuanglongAccelerationModel$att[7,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[7,7,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[7,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[7,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[7,7,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[7,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulatedDataAccAsMatrix[7,] ~ sim_time)
legend("bottomright", legend = c(expression(p[z] ~ " state"), expression("simulated " ~ p[z]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))


plot(simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax] ~ sim_time, pch  = 20, main = expression(v[z] ~ " in simulation"), ylab = expression(v[z] ~" in m/s"),xlab="t in s", type='l', ylim=c(
  min(simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax]) - plot_limit_offset,
  max(simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[8,8,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[8,8,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[8,1:simulatedMax] ~ sim_time, col = "blue")
legend("bottomright", legend = c(expression(v[z] ~ " state"), "process uncertainty"), lwd = 3, col = c("blue", "lightsteelblue"))


plot(simulationAccelerationMeasurementsAsMatrix[6,] ~ sim_time, pch  = 20, main = expression(a[z] ~ " in simulation"), ylab = expression(a[z] ~" in m/" ~ s^2),xlab="t in s", type='l', ylim=c(
  min(simulationAccelerationMeasurementsAsMatrix[6,], simulatedfkfGuanglongAccelerationModel$att[9,1:simulatedMax]) - plot_limit_offset,
  max(simulationAccelerationMeasurementsAsMatrix[6,], simulatedfkfGuanglongAccelerationModel$att[9,1:simulatedMax]) + plot_limit_offset))
polygon(
  x = c(sim_time, rev(sim_time)),
  y = c(simulatedfkfGuanglongAccelerationModel$Ptt[9,9,1:simulatedMax] + simulatedfkfGuanglongAccelerationModel$att[9,1:simulatedMax], rev(simulatedfkfGuanglongAccelerationModel$att[9,1:simulatedMax] - simulatedfkfGuanglongAccelerationModel$Ptt[9,9,1:simulatedMax] )),
  col = "lightsteelblue",
  border = NA)
lines(simulatedfkfGuanglongAccelerationModel$att[9,1:simulatedMax] ~ sim_time, col = "blue")
lines(simulationAccelerationMeasurementsAsMatrix[6,] ~ sim_time)
legend("bottomright", legend = c(expression(a[z] ~ " state"), expression("simulated " ~ a[z]), "process uncertainty"), lwd = 3, col = c("blue", "black", "lightsteelblue"))

#plot(simulatedfkfGuanglongAccelerationModel, type = "resid.qq")
```


```{r}
print(params)
```

