Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 16384
    v.cpus = 4
    v.gui = true
    v.name = "kinect"
  end

#Add camera drivers for the box
 config.vm.provision "shell", inline: <<-SHELL
    sudo apt install libdigest-sha-perl -y
    sudo apt install libproc-processtable-perl -y
    git clone --depth=1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux_media
    cd media_build && ./build
    sudo make install 
    sudo make unload
    modprobe uvcvideo
    cd ..
  SHELL

## Pull Python, AlphaPose-CPU 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install git cmake build-essential libusb-1.0-0-dev -y
    sudo apt-get install freeglut3-dev libxmu-dev libxi-dev -y
    git clone https://github.com/OpenKinect/libfreenect
    cd libfreenect
    mkdir build
    cd build
    cmake -L ..
    make
  SHELL

# Install GUI
  config.vm.provision "shell", inline: "sudo sed -i 's/^# deb/deb/g' /etc/apt/sources.list" 
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
  config.vm.provision "shell", inline: "sudo loadkeys fr"
  config.vm.provision "shell", inline: "sudo apt-get install -y gnome-session gdm3"
  config.vm.provision "shell", inline: "sudo sed -i 's/XKBLAYOUT=\"us\"/XKBLAYOUT=\"fr\"/g' /etc/default/keyboard" 
  config.vm.provision "shell", inline: "sudo apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"
  config.vm.provision "shell", inline: "sudo shutdown -r now"
end