Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 16384
    v.cpus = 4
    v.gui = true
    v.name = "open-pose-gpu"
  end

#Add camera drivers for the box
# config.vm.provision "shell", inline: <<-SHELL
#    sudo apt install libdigest-sha-perl libproc-processtable-perl -y
#    git clone --depth=1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux_media
#    cd media_build && ./build
#    sudo make install
#    sudo make unload
#    modprobe uvcvideo
#    cd ..
#  SHELL

## Pull Python, AlphaPose-CPU 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt install nvidia-cuda-toolkit git cmake -y
    sudo add-apt-repository ppa:deadsnakes/ppa -y
    sudo apt update 
    sudo apt install build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev -y
    

    git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose

    echo "Now provide the models"
  SHELL

# Install GUI
#  config.vm.provision "shell", inline: "sudo sed -i 's/^# deb/deb/g' /etc/apt/sources.list" 
#  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
#  config.vm.provision "shell", inline: "sudo loadkeys fr"
#  config.vm.provision "shell", inline: "sudo apt-get install -y gnome-session gdm3"
#  config.vm.provision "shell", inline: "sudo sed -i 's/XKBLAYOUT=\"us\"/XKBLAYOUT=\"fr\"/g' /etc/default/keyboard" 
#  config.vm.provision "shell", inline: "sudo apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"
#  config.vm.provision "shell", inline: "sudo shutdown -r now"
end